# Generated by Django 4.2.7 on 2023-12-03 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jersey_number', models.IntegerField(max_length=99)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_conditions', models.TextField(blank=True, null=True)),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_club', to='app.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_club', to='app.club')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(default='6a9aed5f', max_length=8, unique=True)),
                ('contract_type', models.CharField(choices=[('standard', 'Стандартный'), ('rental', 'Аренда')], max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_conditions', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transfer')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
