# Generated by Django 4.2.7 on 2023-12-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='player',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(default='a61f46ac', max_length=8, unique=True),
        ),
    ]
