# Generated by Django 4.2.7 on 2023-12-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contract_contract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(default='c1bd4363', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
