# Generated by Django 4.2.7 on 2023-12-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contract_contract_id_alter_country_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(default='ef58a937', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transfer'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(),
        ),
    ]
