# Generated by Django 4.2.7 on 2023-12-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contract_contract_id_alter_contract_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(default='5d7564ea', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_club', to='app.club'),
        ),
    ]
