# Generated by Django 4.2.7 on 2023-12-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contract_contract_id_alter_transfer_from_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(default='c5202e95', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateField(),
        ),
    ]
