# Generated by Django 4.2.7 on 2023-12-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_contract_contract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(default='28ca3739', max_length=8, unique=True),
        ),
    ]
